x-constants:
  db_username: &db_username participium
  db_password: &db_password participium
  backend_url: &backend_url http://localhost:8080/api/v1

name: Participium-Dev
services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    container_name: db-dev
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: participium
      MYSQL_USER: *db_username
      MYSQL_PASSWORD: *db_password
    ports:
      - "3306:3306" # MySQL port
    volumes:
      - mysql-data:/var/lib/mysql # Persist MySQL data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

# Backend service: Runs a Dockerfile located in the backend directory.
  backend:
    image: vanni1888/participium-g15:backend
    container_name: backend-dev
    environment:
      DB_TYPE: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: participium
      DB_USERNAME: *db_username
      DB_PASSWORD: *db_password
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped
    # This command runs after the db is initialized and ready.
    command: sh -c "npm run start"

  frontend:
    image: vanni1888/participium-g15:frontend
    container_name: frontend-dev
    environment:
      VITE_BACKEND_URL: *backend_url
    depends_on:
      backend:
        condition: service_started
    restart: unless-stopped
    ports:
      - "5173:5173" # Anchored variables defined above (e.g., &frontend_port) cannot be used within quoted strings.
        # Values like port numbers must be written explicitly as literals, but they should remain consistent with the defined variables.

volumes:
  mysql-data: